name: build-guest
description: Build guest app
# inputs:
#   service-folder:
#     description: Folder containing serverless.yml to be deployed
#     required: true
#   stage:
#     description: Stage to be deployed to
#     required: true

runs:
  using: 'composite'
  defaults:
    shell: bash
    run:
      working-directory: apps/guest
  steps:
    - name: Pre-build
      run: npm ci
    - name: 'Build guest app'
      run: |
        npm run build
