name: build-guest
description: Build guest app
# inputs:
#   service-folder:
#     description: Folder containing serverless.yml to be deployed
#     required: true
#   stage:
#     description: Stage to be deployed to
#     required: true

runs:
  using: 'composite'
  steps:
    - name: Pre-build
      # should specify working-directory, shell for every step (in composite run)
      working-directory: apps/guest
      shell: bash
      run: npm ci
    - name: 'Build guest app'
      working-directory: apps/guest
      shell: bash
      run: |
        npm run build
