name: build-shop
description: Build shop app
# inputs:
#   service-folder:
#     description: Folder containing serverless.yml to be deployed
#     required: true
#   stage:
#     description: Stage to be deployed to
#     required: true

runs:
  using: "composite"
  steps:
    - name: Pre-build
      # should specify working-directory, shell for every step (in composite run)
      working-directory: apps/shop
      shell: bash
      run: npm ci
    - name: "Build shop app"
      working-directory: apps/shop
      shell: bash
      run: |
        DISABLE_ESLINT_PLUGIN=true npm run build
