# swagger: '2.0'
openapi: 3.0.0
info:
  $ref: ./info/index.yaml
servers:
  $ref: ./info/servers.yaml
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /oauth/dialog
          tokenUrl: /oauth/token