name: build-app
description: Build app
inputs:
  app-folder:
    description: Folder containing react app to be built
    required: true
#   stage:
#     description: Stage to be deployed to
#     required: true

env:
  REACT_APP_COGNITO_CLIENT_ID: ${{ secrets.REACT_APP_COGNITO_CLIENT_ID }}
  REACT_APP_COGNITO_LOGIN_URL: ${{ secrets.REACT_APP_COGNITO_LOGIN_URL }}

runs:
  using: "composite"
  steps:
    - name: Pre-build
      # should specify working-directory, shell for every step (in composite run)
      working-directory: ${{ inputs.app-folder }}
      shell: bash
      run: npm ci
    - name: "Build app"
      working-directory: ${{ inputs.app-folder }}
      shell: bash
      run: |
        npm run build
